logging:
  level:
    root: warn
    kr.co.picTO: info

  logback:
    rollingpolicy:
      max-history: 7

server:
  port: 8080
  servlet:
    context-path: /picTOmaker.com

spring:
  profiles: dev
    include: private
