logging:
  level:
    root: warn
    kr.co.picTO: debug #debug info warn error fatal off

server:
  port: 8080
  servlet:
    context-path: /picTOmaker.com

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/picTO/maker
    driver-class-name: org.h2.Driver
    username: sa

  messages:
    basename: i18n/exception
    encoding: UTF-8

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hbm2ddl.auto: update
      format_sql: true
    show-sql: true
    generate-ddl: true
    open-in-view: false

  url:
    base: http://localhost:8080

  config:
    activate:
      on-profile: local

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher