spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

  datasource:
    url: jdbc:h2:tcp://localhost/~/picTO/maker
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.hbm2ddl.auto: create
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  messages:
    basename: i18n/exception
    encoding: UTF-8

  profiles:
    include: jwt

logging:
  level:
    root: debug
    org.hibernate.SQL: debug

server:
  port: 8080
  servlet:
    context-path: /picTO
